name = "gist-id-edge"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-01"

routes = [
    { pattern = "gist.id/*", zone_name = "gist.id" }
]

[build]
command = "(command -v worker-build || cargo install -q worker-build) && worker-build --release"
